#!/bin/sh
# prerm script for gnome-app-install

set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ] ; then
    update-alternatives --remove \
        gstreamer-codec-install /usr/bin/gnome-app-install || true
fi

#DEBHELPER#

exit 0

