#!/bin/sh

item="/usr/bin/gnome-panel"

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" -o abort-upgrade = "$1" ]
then
    [ -f "$item"".real" ] && dpkg-divert --package trisquel-desktop-common-data --remove --rename --divert "$item"".real" "$item"
fi
