#!/bin/sh

# make sure apt knows about the new keys
if [ -x /usr/bin/apt-key ]; then
    /usr/bin/apt-key add /usr/share/keyrings/trisquel-archive-keyring.gpg
    /usr/bin/apt-key update
fi

# the keyring in /var that gets fetched by apt-key net-update
# if it does not yet exist, copy it to avoid uneeded net copy
KEYRINGDIR="/var/lib/apt/keyrings"
KEYRING="${KEYRINGDIR}/trisquel-archive-keyring.gpg"

if ! test -d $KEYRINGDIR; then
     mkdir -m 755 -p $KEYRINGDIR
fi

if ! test -f $KEYRING; then
     cp /usr/share/keyrings/trisquel-archive-keyring.gpg $KEYRING
     touch $KEYRING
fi
